docs: improve doc related to env files
graasp/graasp-player pull request #213
Opened 2023-03-16 17:34 UTC by spaenleh

2023-03-16 21:45 UTC, dialexo requested changes
Would these changes make sense?

2023-03-16 21:45 UTC, dialexo commented on README.md
> +VITE_GRAASP_BUILDER_HOST=http://localhost:3001
```suggestion
VITE_GRAASP_BUILDER_HOST=http://localhost:3111
```

2023-03-17 07:47 UTC, spaenleh commented
@dialexo Yes totally! Thank you !

2023-03-17 08:20 UTC, dialexo approved these changes

2023-03-17 08:23 UTC, merged